version: '2.4'

services:

  frontend:
    image: "grocy/frontend:${GROCY_IMAGE_TAG}"
    build:
      args:
        GROCY_VERSION: v3.2.0
        PLATFORM: linux/amd64
      context: .
      dockerfile: Dockerfile-grocy-frontend
    depends_on:
      - backend
    ports:
      - '127.0.0.1:80:49155'
      - '127.0.0.1:443:49156'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx

  backend:
    image: "grocy/backend:${GROCY_IMAGE_TAG}"
    build:
      args:
        GROCY_VERSION: v3.2.0
        PLATFORM: linux/amd64
        COMPOSER_VERSION: "2.1.5"
        COMPOSER_CHECKSUM: "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
      context: .
      dockerfile: Dockerfile-grocy-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php8
      - app-db:/var/www/data
    env_file:
      - grocy.env

volumes:
  app-db:
